# Generated by Django 4.1 on 2023-06-20 13:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0002_alter_conversation_id_alter_question_id"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="conversation",
            table="conversations",
        ),
        migrations.AlterModelTable(
            name="question",
            table="questions",
        ),
    ]
