# Generated by Django 4.1 on 2023-06-20 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("conversation", models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("question", models.CharField(max_length=255)),
                ("options", models.CharField(max_length=500)),
                ("answer", models.CharField(max_length=255)),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="myapp.conversation",
                    ),
                ),
            ],
        ),
    ]
