# Generated by Django 4.1 on 2023-06-22 21:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("myapp", "0005_useranswer_userfeedback"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserAnswer",
        ),
        migrations.DeleteModel(
            name="UserFeedback",
        ),
        migrations.DeleteModel(
            name="AuthGroup",
        ),
        migrations.DeleteModel(
            name="AuthGroupPermissions",
        ),
        migrations.DeleteModel(
            name="AuthPermission",
        ),
        migrations.DeleteModel(
            name="AuthUser",
        ),
        migrations.DeleteModel(
            name="AuthUserGroups",
        ),
        migrations.DeleteModel(
            name="AuthUserUserPermissions",
        ),
        migrations.DeleteModel(
            name="Conversations",
        ),
        migrations.DeleteModel(
            name="DjangoAdminLog",
        ),
        migrations.DeleteModel(
            name="DjangoContentType",
        ),
        migrations.DeleteModel(
            name="DjangoMigrations",
        ),
        migrations.DeleteModel(
            name="DjangoSession",
        ),
        migrations.DeleteModel(
            name="MyappConversation",
        ),
        migrations.DeleteModel(
            name="MyappQuestion",
        ),
        migrations.DeleteModel(
            name="Questions",
        ),
    ]
