# Generated by Django 4.1 on 2023-06-22 21:48

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("myapp", "0006_delete_useranswer_delete_userfeedback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversations",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("conversation", models.TextField(blank=True, null=True)),
                ("fre", models.FloatField(blank=True, null=True)),
                ("fkgl", models.FloatField(blank=True, null=True)),
            ],
            options={
                "db_table": "conversations",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="Questions",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("question", models.TextField(blank=True, null=True)),
                ("options", models.TextField(blank=True, null=True)),
                ("answer", models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                "db_table": "questions",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserAnswer",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(blank=True, max_length=36, null=True)),
                ("answer", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "real_answer",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_answer",
                "managed": False,
            },
        ),
        migrations.CreateModel(
            name="UserFeedback",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(blank=True, max_length=36, null=True)),
                ("feedback1", models.CharField(blank=True, max_length=255, null=True)),
                ("feedback2", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "user_feedback",
                "managed": False,
            },
        ),
    ]
